name: Bot

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 22 * * *'

env:
  TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
  TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
  TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
  TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
  INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  ci:
    strategy:
      fail-fast: false

    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.0
      - name: Installation
        run: poetry install
      - name: Test
        run: poetry run python -m unittest
        continue-on-error: true
      - name: Favorite
        run: poetry run python favorite.py
      - name: Tweet
        if: ${{ github.event_name == 'schedule' }}
        run: poetry run python main.py
      - name: Retweet
        if: ${{ github.event_name == 'schedule' }}
        run: poetry run python retweet.py


      - name: Slack Notification on Success
        if: success()
        uses: tokorom/action-slack-incoming-webhook@master
        with:
          text: Success
          attachments: |
            [
              {
                "color": "good",
                "fields": [
                  {
                    "title": "GitHub Actions URL",
                    "value": "${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"
                  }
                ]
              }
            ]

      - name: Slack Notification on Failure
        if: failure()
        uses: tokorom/action-slack-incoming-webhook@master
        with:
          text: Failure
          attachments: |
            [
              {
                "color": "danger",
                "fields": [
                  {
                    "title": "GitHub Actions URL",
                    "value": "${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"
                  }
                ]
              }
            ]

      - name: Commit Files
        run: |
          bash update.sh
          git add -A
          git config user.name github-actions
          git config user.email github-actions@github.com
          now=`TZ=JST-9 date`
          git commit -m "${now}"
          git push